INSERT INTO items (name, price, quantity, category)
VALUES 
("Organic Marble Printed Shower Curtain", 49, 5, "Home"),
("Silk Hand-Loomed Pillow Covers", 24.99, 40, "Home"),
("Geometric Wall Hooks", 59, 20, "Home"),
("GoWeave Essential Jumpsuit", 120, 5, "Clothing"),
("Cotton-Linen Crew", 60, 100, "Clothing"),
("Tie-Dye Box-Cut Tee", 25, 50, "Clothing"),
("Soft Wool Rib Scarf", 65, 30, "Accessories"),
("Mixed-Print Bandana", 18, 10, "Accessories"),
("Acacia Kimono", 98, 8, "Accessories"),
("Powder Blush in Peaches", 23, 100, "Beauty"),
("Razor Sharp Liquid Eyeliner", 22, 30, "Beauty"),
("Brow Power Universal Eyebrow Pencil", 24, 100, "Beauty"),
("Table Lamp", 80, 50, "Home"),
("Sweater Rug", 149, 5, "Home"),
("Rounded Terracotta Floor Vases", 89, 10, "Home"),
("Flax Linen Duvet Cover", 171, 20, "Home"),
("Metal Framed Wall Mirror", 299, 5, "Home"),
("Shirred Silk Shirt", 98, 10, "Clothing"),
("Skirted Wide Leg Pants", 130, 4, "Clothing"),
("Square Neck Swimsuit", 130, 100, "Clothing"),
("Wrap Dress", 100, 200, "Clothing"),
("Pleated Skirt", 160, 30, "Clothing"),
("Choker Necklace Jewelry", 15, 100, "Accessories"),
("Patent Square Toe Block Heeled Sandals", 99.95, 50, "Accessories"),
("Straw Sun Hat with Wide Band", 39, 20, "Accessories"),
("Tote Bag", 44.50, 200, "Accessories"),
("Aviator Sunglasses", 130, 40, "Accessories"),
("Double Wear Foundation", 24.99, 50, "Beauty"),
("Satin Lipstick", 18.50, 30, "Beauty"),
("Roller Lash Mascara", 25, 100, "Beauty"),
("Shape Tape Concealer", 27, 30, "Beauty"),
("You Glow Girl Highlighter", 9, 5, "Beauty");