INSERT INTO items (name, price, quantity, category, createdAt, updatedAt, img)
VALUES 

("Printed Shower Curtain", 49, 5, "Home", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, "/img/organic-marble-printed-shower-curtain-c.jpg"),
("Silk Pillow Covers", 24.99, 40, "Home", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, "/img/silk-hand-loomed-pillow-covers-c.jpg"),
("Geometric Wall Hooks", 59, 20, "Home", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, "/img/geometric-wall-hooks-brass-white-c.jpg"),
("GoWeave Jumpsuit", 120, 5, "Clothing", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, "/img/goweave-wrap-jumpsuit.jpg"),
("Cotton-Linen Crew", 60, 100, "Clothing", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, "/img/crew-sweater.jpg"),
("Tie-Dye Box-Cut Tee", 25, 50, "Clothing", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, "/img/box-cut-tee.jpg"),
("Soft Wool Rib Scarf", 65, 30, "Accessories", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, "/img/scarf.jpg"),
("Mixed-Print Bandana", 18, 10, "Accessories", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, "/img/mixed-print-bandana.jpg"),
("Square Toe Sandals", 99.95, 50, "Accessories", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, "/img/patent-block-heel-shoe.jpg"),
("Roller Lash Mascara", 25, 100, "Beauty", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, "/img/roller_lash_mascara_black.jpg"),
("Shape Tape Concealer", 27, 30, "Beauty", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, "/img/shape tape concealer_35N_medium_DDB_misc-alt-1_ALT.jpg"),
("Glow Girl Highlighter", 9, 5, "Beauty", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, "/img/you-glow-girl-highlighter.jpg"),
("Blush in Peaches", 23, 100, "Beauty", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, "/img/peach-blush.jpg"),
("Liquid Eyeliner", 22, 30, "Beauty", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, "/img/razorsharp-eyeliner.jpg"),
("Brow Power Pencil", 24, 100, "Beauty", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, "/img/brows-brow-power-original-pack-shot.jpg"),
("Table Lamp", 80, 50, "Home", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, "/img/table-lamp-c.jpg"),
("Sweater Rug", 149, 5, "Home", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, "/img/sweater-wool-rug-charcoal-c.jpg"),
("Terracotta Floor Vases", 89, 10, "Home", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, "/img/rounded-terracotta-floor-vases-c.jpg"),
("Flax Linen Duvet Cover", 171, 20, "Home", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, "/img/flax-linen-melange-duvet-cover-shams-c.jpg"),
("Framed Wall Mirror", 299, 5, "Home", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, "/img/mirror.jpg"),
("Shirred Silk Shirt", 98, 10, "Clothing", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, "/img/shirred-silk-shirt.jpg"),
("Wrap Dress", 100, 200, "Clothing", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, "/img/wrap-dress.jpg"),
("Pleated Skirt", 160, 30, "Clothing", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, "/img/pleated-skirt.jpg"),
("Skirted Wide Leg Pants", 130, 4, "Clothing", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, "/img/skirted-wide-leg-pants.jpg"),
("Square Neck Swimsuit", 130, 100, "Clothing", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, "/img/square-neck-swimsuit.jpg"),
("Choker Necklace", 15, 100, "Accessories", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, "/img/choker-necklace.jpg"),
("Tote Bag", 44.50, 200, "Accessories", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, "/img/tote-bag.jpg"),
("Aviator Sunglasses", 130, 40, "Accessories", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, "/img/aviator-sunglasses.jpg"),
("Long Wear Foundation", 24.99, 50, "Beauty", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, "/img/double-wear-foundation.png"),
("Satin Lipstick", 18.50, 30, "Beauty", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, "/img/satin-lipstick.jpg"),
("Acacia Kimono", 98, 8, "Accessories", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, "/img/kimono.jpg");